---
title: "Preliminary Results - 11/06/2025"
format:
  html:
    page-layout: full
    # optional: keep text from getting too wide
    # css: styles.css
    code-overflow: scroll
editor: source
execute: 
  warning: false
  echo: false
---


```{r}
rm(list=ls())
library(data.table)
library(fixest)
library(DescTools)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(readxl)
library(stringr)

source('https://raw.githubusercontent.com/dratnadiwakara/r-utilities/refs/heads/main/summary_stat_tables.R')
```


```{r}
call <- readRDS("C:/data/fdic_call_report_2000_2025.rds")
call <- call[month(REPDTE)==12]
call[,YEAR:=year(REPDTE)]

call <- call %>%
  arrange(RSSDID, YEAR) %>%
  group_by(RSSDID) %>%
  mutate(
    lead_DEPDOM1 = dplyr::lead(DEPDOM, 1),
    lead_DEPDOM3 = dplyr::lead(DEPDOM, 3),
    lag_DEPDOM3 = dplyr::lag(DEPDOM, 2),
    delta_DEPDOM_deposits = (lead_DEPDOM3 - lead_DEPDOM1) / lead_DEPDOM1,
    delta_DEPDOM_assets = (lead_DEPDOM3 - lead_DEPDOM1) / ASSET,
    loans_assets = LNLSGR/ASSET,
    DEPFOR = ifelse(is.na(DEPFOR),0, DEPFOR),
    deposits_assets = (DEPDOM+DEPFOR)/ASSET,
    nim_assets = NIM/ASSET,
    roe = NETINC/EQ2,
    equity_assets = EQ2/ASSET,
    log_assets = log(ASSET)
  ) %>% data.table()

call[,delta_DEPDOM_deposits_w := Winsorize(delta_DEPDOM_deposits, val = quantile(delta_DEPDOM_deposits, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]
call[,delta_DEPDOM_assets_w := Winsorize(delta_DEPDOM_assets, val = quantile(delta_DEPDOM_assets, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]

```


```{r}
open_close <- readRDS("C:/data/bank_year_panel_branch_dynamics.rds")

df <- merge(open_close,
            call,
            by=c("RSSDID","YEAR"))

# df2 <- df[frac_closed_last3>0 | frac_opened_last3>0]
df[,frac_closed_last3 := Winsorize(frac_closed_last3, val = quantile(frac_closed_last3, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]
df[,frac_opened_last3 := Winsorize(frac_opened_last3, val = quantile(frac_opened_last3, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]
df[,share_existing_closed_last3:=Winsorize(share_existing_closed_last3, val = quantile(share_existing_closed_last3, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]
df[,share_recent_acq_closed_last3:=Winsorize(share_recent_acq_closed_last3, val = quantile(share_recent_acq_closed_last3, probs = c(0.01, 0.99), na.rm = T)),by=YEAR]
df[,closed_last3_dummy:=ifelse(frac_closed_last3>0,1,0)]
df[,opened_last3_dummy:=ifelse(frac_opened_last3>0,1,0)]

```


# Descriptive Stats

## Dependent Variable: (Deposits$_{t+3}$ - Deposits$_{t+1}$)/Assets$_t$

```{r}
ggplot(df[YEAR>2001 & YEAR<2022],aes(x=delta_DEPDOM_assets_w))+geom_histogram()+facet_wrap(~YEAR)
```
## Key RHS Variables (previous three years)

```{r}
g1 <- ggplot(df,aes(x=frac_closed_last3))+geom_histogram()
g2 <- ggplot(df,aes(x=frac_opened_last3))+geom_histogram()
grid.arrange(g1,g2,nrow=1)
```


## Summary Stats
```{r}
temp <- summary_stats_function(df[YEAR==2019],c("delta_DEPDOM_assets_w","frac_closed_last3","frac_opened_last3","share_existing_closed_last3","share_recent_acq_closed_last3",
                            "closed_last3_dummy","opened_last3_dummy","log_assets","equity_assets","roe","nim_assets","deposits_assets","loans_assets"))

md_table(temp)
```


```{r}
setFixest_fml(..ctrl_basic=~log_assets+equity_assets+roe+nim_assets+deposits_assets+loans_assets)
setFixest_etable(se.below = T,
                 order = c("frac_closed_last3","share_existing_closed_last3","share_recent_acq_closed_last3","closed_last3","frac_opened_last3","opened_last3"),
                 depvar = F)


```


# Results

## Baseline
```{r}
r <- list()
r[[1]] <- feols(delta_DEPDOM_assets_w~frac_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df,vcov = ~RSSDID)
r[[2]] <- feols(delta_DEPDOM_assets_w~frac_closed_last3+frac_opened_last3+..ctrl_basic|RSSDID+YEAR,data=df,vcov = ~RSSDID)

r[[3]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df,vcov = ~RSSDID)
r[[4]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|RSSDID+YEAR,data=df,vcov = ~RSSDID)


r[[5]] <- feols(delta_DEPDOM_assets_w~closed_last3_dummy+opened_last3_dummy+..ctrl_basic|YEAR,data=df,vcov = ~RSSDID)
r[[6]] <- feols(delta_DEPDOM_assets_w~closed_last3_dummy+opened_last3_dummy+..ctrl_basic|RSSDID+YEAR,data=df,vcov = ~RSSDID)

md_table(etable(r, tex = FALSE)) 
```

## By Regime
```{r}
r <- list()

r[[1]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df[YEAR %in% 2003:2007],vcov = ~RSSDID)
r[[2]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df[YEAR %in% 2008:2011],vcov = ~RSSDID)
r[[3]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df[YEAR %in% 2012:2019],vcov = ~RSSDID)
r[[4]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3+share_recent_acq_closed_last3+frac_opened_last3+..ctrl_basic|YEAR,data=df[YEAR %in% 2020:2021],vcov = ~RSSDID)



md_table(etable(r,headers = c("2003:2007","2008:2011","2012:2019","2020:2021")))
```


```{r}
acs_data <- readRDS("C:/data/acs_data_2010_2022_tract.rds")

tract_zip_crosswalk <- read_excel('C:/data/ZIP_TRACT_122019.xlsx')
tract_zip_crosswalk <- data.table(tract_zip_crosswalk)
tract_zip_crosswalk[,zip:=str_pad(ZIP,5,"left","0")]
tract_zip_crosswalk[,tract:=as.character(TRACT)]
tract_zip_crosswalk[,tract:=str_pad(tract,11,"left","0")]
tract_zip_crosswalk[,tot_ratio:=TOT_RATIO]


acs_with_zip <- acs_data %>%
  left_join(tract_zip_crosswalk[,c("zip","tract","tot_ratio")], by = c("tract" = "tract"))



zip_aggregated_data <- acs_with_zip %>%
  group_by(zip,yr) %>%
  summarize(
    # Weighted average of median income
    median_income = sum(median_income * tot_ratio, na.rm = T) ,

    # Weighted average of percentage of population with a bachelor's degree
    pct_college_educated = sum(pct_college_educated * tot_ratio, na.rm=T),

    # Weighted average of white population percentage
    # white_population_pct = sum(white_populationE * RES_RATIO,na.rm=T),

    # Weighted average of median age
    median_age = sum(median_age * tot_ratio,na.rm = T)

    # Total population is weighted by RES_RATIO
    # total_population = sum(total_populationE * RES_RATIO)
  )

zip_aggregated_data <- data.table(zip_aggregated_data)

irs_data <- readRDS("C:/data/irs_data_2010_2022_zip.rds")


irs_data <- irs_data[,c("zipcode","yr","dividend_frac","capital_gain_frac")]
irs_data[,zipcode:=str_pad(zipcode,5,"left","0")]
# 
zip_demo_data <- merge(zip_aggregated_data,irs_data,by.x=c("zip","yr"),by.y=c("zipcode","yr"),all.x=T)


key_chars <- c("median_income","median_age","pct_college_educated","capital_gain_frac","dividend_frac")

zip_demo_data <- data.table(zip_demo_data)
zip_demo_data[,paste0(key_chars,"_q"):=lapply(.SD, function(x) ntile(x,2)),by=yr,.SDcols = key_chars]

zip_demo_data[,sophisticated_ed_sm:=ifelse(!is.na(dividend_frac)  & pct_college_educated_q==2 & (dividend_frac_q==2 | capital_gain_frac_q==2),1,
                                     ifelse(!is.na(dividend_frac),0,NA))]


zip_demo_data <- zip_demo_data[,c("zip","yr","median_income","median_age","pct_college_educated","capital_gain_frac","dividend_frac","sophisticated_ed_sm")]

zip_demo_data[,age_bin:=ntile(median_age,4),by=yr]

temp1 <- zip_demo_data[yr==2010]
for(y in 2000:2009) {
  temp <- copy(temp1)
  temp[,yr:=y]
  zip_demo_data <- rbind(zip_demo_data,temp)
}

temp1 <- zip_demo_data[yr==2022]
for(y in 2023:2024) {
  temp <- copy(temp1)
  temp[,yr:=y]
  zip_demo_data <- rbind(zip_demo_data,temp)
}

temp1 <- zip_demo_data[yr==2010]
for(y in 2011:2012) {
  temp <- copy(temp1)
  temp[,yr:=y]
  zip_demo_data <- rbind(zip_demo_data,temp)
}

temp1 <- zip_demo_data[yr==2013]
for(y in 2014:2015) {
  temp <- copy(temp1)
  temp[,yr:=y]
  zip_demo_data <- rbind(zip_demo_data,temp)
}

temp1 <- zip_demo_data[yr==2019]
for(y in 2020:2021) {
  temp <- copy(temp1)
  temp[,yr:=y]
  zip_demo_data <- rbind(zip_demo_data,temp)
}


all_sod <- readRDS(file = "C:/data/fdic_sod_2000_2025.rds")
all_sod <- all_sod[,.(ZIPBR,UNINUMBR, RSSDID,DEPSUMBR,YEAR)]

all_sod <- merge(all_sod,zip_demo_data,
              by.x=c("ZIPBR","YEAR"),
              by.y=c("zip","yr"))

all_sod[,total_deposits_bank_year:=sum(DEPSUMBR,na.rm=T),by=.(RSSDID,YEAR)]
all_sod[,deposit_w:=DEPSUMBR/total_deposits_bank_year]
all_sod[,sophisticated_w:=sophisticated_ed_sm*deposit_w]

sophisticated_bank_year <- all_sod[,.(sophisticated_w=sum(sophisticated_w,na.rm=T)),by=.(RSSDID,YEAR)]
```


```{r}
df2 <- merge(df,
             sophisticated_bank_year,
             by.x=c("RSSDID","YEAR"),
             by.y=c("RSSDID","YEAR"),all.x=T)
```

## Interaction with frac deposits in sophisticated zip codes
```{r}
r <- list()
r[[1]] <- feols(delta_DEPDOM_assets_w~frac_closed_last3*sophisticated_w+frac_opened_last3*sophisticated_w+..ctrl_basic|YEAR,data=df2,vcov = ~RSSDID)
r[[2]] <- feols(delta_DEPDOM_assets_w~frac_closed_last3*sophisticated_w+frac_opened_last3*sophisticated_w+..ctrl_basic|RSSDID+YEAR,data=df2,vcov = ~RSSDID)

r[[3]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3*sophisticated_w+share_recent_acq_closed_last3*sophisticated_w+frac_opened_last3*sophisticated_w+..ctrl_basic|YEAR,data=df2,vcov = ~RSSDID)
r[[4]] <- feols(delta_DEPDOM_assets_w~share_existing_closed_last3*sophisticated_w+share_recent_acq_closed_last3*sophisticated_w+frac_opened_last3*sophisticated_w+..ctrl_basic|RSSDID+YEAR,data=df2,vcov = ~RSSDID)


r[[5]] <- feols(delta_DEPDOM_assets_w~closed_last3_dummy*sophisticated_w+opened_last3_dummy*sophisticated_w+..ctrl_basic|YEAR,data=df2,vcov = ~RSSDID)
r[[6]] <- feols(delta_DEPDOM_assets_w~closed_last3_dummy*sophisticated_w+opened_last3_dummy*sophisticated_w+..ctrl_basic|RSSDID+YEAR,data=df2,vcov = ~RSSDID)

md_table(etable(r))
```